services:
  db:
    image: postgis/postgis:15-3.3 # Phiên bản Postgres 15 kèm PostGIS
    container_name: missingu_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: missingu_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: